"""turn embedding column for RAG

Revision ID: fc0a01f4b7da
Revises: 6caac37ae4b1
Create Date: 2026-07-07 00:20:45.950165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0a01f4b7da'
down_revision: Union[str, Sequence[str], None] = '6caac37ae4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'embedding')
    # ### end Alembic commands ###
