"""Temporal CFI Transformer (Phase 2, pillar 2) — trajectory modeling.

Predicts the NEXT-turn distortion vector from the history of turns, moving the
project from static classification to cognitive-dynamics modeling. CFI itself is
always derived from the predicted vector via compute_cfi() — one definition of CFI
everywhere.

Deliberately small (2 layers, d_model=32): the training set is ~49 synthetic
dialogues of ~4 client turns each.

LIMITATION (disclose, same pattern as weak labeling): trained on SYNTHETIC dialogue
trajectories generated by an LLM, not real longitudinal user data. This validates
the architecture, not clinical dynamics. The honest benchmark is the persistence
baseline (predict next = last observed); results are reported win or lose.

Train: python -m src.models.temporal_cfi train
"""

from __future__ import annotations

import argparse
import json
import math
import random
from pathlib import Path

import torch
from torch import nn

from src.metrics.cognitive_flexibility_index import compute_cfi
from src.utils.config import PROJECT_ROOT, load_config, taxonomy_labels
from src.utils.logging_config import get_logger

logger = get_logger(__name__)


def _positional_encoding(max_len: int, d_model: int) -> torch.Tensor:
    pe = torch.zeros(max_len, d_model)
    pos = torch.arange(max_len).unsqueeze(1).float()
    div = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
    pe[:, 0::2] = torch.sin(pos * div)
    pe[:, 1::2] = torch.cos(pos * div)
    return pe


class TemporalCFITransformer(nn.Module):
    """Causal encoder over turn-level distortion vectors -> next-turn prediction."""

    def __init__(self, n_labels: int = 5, d_model: int = 32, n_heads: int = 4,
                 n_layers: int = 2, dropout: float = 0.1, max_len: int = 64):
        super().__init__()
        self.n_labels = n_labels
        self.input_proj = nn.Linear(n_labels, d_model)
        self.register_buffer("pos_enc", _positional_encoding(max_len, d_model))
        layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=n_heads, dim_feedforward=d_model * 4,
            dropout=dropout, batch_first=True,
        )
        self.encoder = nn.TransformerEncoder(layer, num_layers=n_layers)
        self.head = nn.Linear(d_model, n_labels)

    def forward(self, x: torch.Tensor, padding_mask: torch.Tensor | None = None) -> torch.Tensor:
        """x: (batch, T, n_labels) -> (batch, T, n_labels) next-turn predictions.

        Position t's output only attends to positions 1..t (causal mask).
        padding_mask: (batch, T) True where PADDED.
        """
        batch, T, _ = x.shape
        h = self.input_proj(x) + self.pos_enc[:T]
        causal = torch.triu(torch.ones(T, T, dtype=torch.bool, device=x.device), diagonal=1)
        h = self.encoder(h, mask=causal, src_key_padding_mask=padding_mask)
        return torch.sigmoid(self.head(h))

    # ------------------------------------------------------------- inference

    @torch.no_grad()
    def predict_next(self, history: list[dict[str, float]]) -> dict[str, float]:
        """history: chronological list of {label: prob} dicts -> predicted next dict."""
        labels = taxonomy_labels()
        self.eval()
        x = torch.tensor(
            [[[h.get(label, 0.0) for label in labels] for h in history]], dtype=torch.float32
        )
        out = self(x)  # (1, T, n_labels)
        pred = out[0, -1]  # prediction for the turn AFTER the last observed
        return {label: float(pred[i]) for i, label in enumerate(labels)}

    # ----------------------------------------------------------- persistence

    @classmethod
    def load(cls, path: str | Path | None = None) -> "TemporalCFITransformer":
        cfg = load_config("model")["temporal_transformer"]
        ckpt_path = Path(path) if path else PROJECT_ROOT / cfg["checkpoint"]
        ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=True)
        model = cls(**ckpt["arch"])
        model.load_state_dict(ckpt["state_dict"])
        model.eval()
        return model


# -------------------------------------------------------------------- training


def _load_sequences() -> list[list[list[float]]]:
    labels = taxonomy_labels()
    data_cfg = load_config("data")
    path = PROJECT_ROOT / data_cfg["paths"]["processed_dir"] / "temporal_sequences.jsonl"
    sequences = []
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        seq = [[t["distortions"].get(label, 0.0) for label in labels] for t in rec["turns"]]
        if len(seq) >= 2:
            sequences.append(seq)
    return sequences


def _collate(seqs: list[list[list[float]]]) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Pad to max length. Returns (inputs, targets, loss_mask):
    inputs = turns 1..T-1, targets = turns 2..T, mask True on REAL positions."""
    n_labels = len(seqs[0][0])
    max_in = max(len(s) - 1 for s in seqs)
    x = torch.zeros(len(seqs), max_in, n_labels)
    y = torch.zeros(len(seqs), max_in, n_labels)
    mask = torch.zeros(len(seqs), max_in, dtype=torch.bool)
    for i, s in enumerate(seqs):
        t = torch.tensor(s, dtype=torch.float32)
        n = len(s) - 1
        x[i, :n] = t[:-1]
        y[i, :n] = t[1:]
        mask[i, :n] = True
    return x, y, mask


def _direction_accuracy(current: torch.Tensor, pred: torch.Tensor, true: torch.Tensor,
                        tol: float = 0.02) -> float:
    """Fraction of (position,label) pairs where predicted change sign matches truth.
    True zero-change counts as correct only when |predicted change| <= tol."""
    pred_d = pred - current
    true_d = true - current
    correct = torch.where(
        true_d.abs() <= 1e-9,
        pred_d.abs() <= tol,
        torch.sign(pred_d) == torch.sign(true_d),
    )
    return float(correct.float().mean())


def train() -> dict:
    cfg = load_config("model")["temporal_transformer"]
    labels = taxonomy_labels()
    torch.manual_seed(cfg["seed"])
    random.seed(cfg["seed"])

    sequences = _load_sequences()
    random.shuffle(sequences)
    n_val = max(1, int(len(sequences) * cfg["val_fraction"]))
    val_seqs, train_seqs = sequences[:n_val], sequences[n_val:]
    logger.info("Sequences: %d train / %d val (session-level split)", len(train_seqs), len(val_seqs))

    model = TemporalCFITransformer(
        n_labels=len(labels), d_model=cfg["d_model"], n_heads=cfg["n_heads"],
        n_layers=cfg["n_layers"], dropout=cfg["dropout"],
    )
    opt = torch.optim.Adam(model.parameters(), lr=cfg["learning_rate"])
    x_tr, y_tr, m_tr = _collate(train_seqs)
    x_va, y_va, m_va = _collate(val_seqs)

    model.train()
    for epoch in range(cfg["epochs"]):
        opt.zero_grad()
        out = model(x_tr, padding_mask=~m_tr)
        loss = ((out - y_tr) ** 2)[m_tr].mean()
        loss.backward()
        opt.step()
        if (epoch + 1) % 50 == 0:
            logger.info("epoch %d: train MSE %.5f", epoch + 1, float(loss))

    # ------------------------------------------------------------ evaluation
    model.eval()
    with torch.no_grad():
        pred_va = model(x_va, padding_mask=~m_va)
    baseline_va = x_va  # persistence: next = last observed

    model_mae = float((pred_va - y_va).abs()[m_va].mean())
    baseline_mae = float((baseline_va - y_va).abs()[m_va].mean())
    metrics = {
        "n_train_sessions": len(train_seqs),
        "n_val_sessions": len(val_seqs),
        "model_mae": round(model_mae, 5),
        "baseline_mae": round(baseline_mae, 5),
        "model_direction_acc": round(
            _direction_accuracy(x_va[m_va], pred_va[m_va], y_va[m_va]), 4),
        "baseline_direction_acc": round(
            _direction_accuracy(x_va[m_va], baseline_va[m_va], y_va[m_va]), 4),
        "beats_baseline_mae": model_mae < baseline_mae,
        "limitation": "trained on synthetic LLM-generated trajectories, not real user data",
    }

    # sample CFI trajectory for the report
    sample = val_seqs[0]
    sample_cfi = [
        round(compute_cfi(dict(zip(labels, turn))), 4) for turn in sample
    ]
    metrics["sample_val_cfi_trajectory"] = sample_cfi

    ckpt_path = PROJECT_ROOT / cfg["checkpoint"]
    ckpt_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "state_dict": model.state_dict(),
            "arch": {
                "n_labels": len(labels), "d_model": cfg["d_model"],
                "n_heads": cfg["n_heads"], "n_layers": cfg["n_layers"],
                "dropout": cfg["dropout"],
            },
            "labels": labels,
        },
        ckpt_path,
    )
    (ckpt_path.parent / "metrics.json").write_text(json.dumps(metrics, indent=2))

    logger.info("Saved checkpoint -> %s", ckpt_path)
    print(json.dumps(metrics, indent=2))
    return metrics


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["train"])
    parser.parse_args()
    train()
